"""Metadata for the eight company document types supplied outside the public repository.

The catalogue intentionally stores field definitions and rendering instructions only. The original
DOCX/PDF source documents are private company/legal assets and are installed through an encrypted
bundle or the administration upload endpoint.
"""

CATALOG_VERSION = '2026.07'

COMMON_PERSON_FIELDS = [
    'salutation', 'first_name', 'last_name', 'email', 'phone', 'street', 'postal_code',
    'city', 'birth_date', 'birth_name', 'birth_place', 'birth_country', 'nationality',
    'social_insurance_number', 'health_insurance_name', 'insurance_type',
    'tax_identification_number', 'iban', 'bank_account_holder', 'bank_name',
]


def field(name, label, source=None, required=False, kind='text', choices=None):
    item = {'name': name, 'label': label, 'type': kind, 'required': required}
    if source:
        item['source'] = source
    if choices:
        item['choices'] = choices
    return item


DOCUMENT_CATALOG = [
    {
        'slug': 'personalfragebogen-standard',
        'name': 'Personalfragebogen A+',
        'kind': 'personnel',
        'audience': 'worker',
        'version': '06.2025',
        'source_format': 'pdf_overlay',
        'source_name': 'Personalfragebogen A+ .pdf',
        'requires_signature': True,
        'signature_roles': ['employee'],
        'fields': [
            field('salutation', 'Anrede', 'master.salutation'),
            field('first_name', 'Vorname', 'user.first_name', True),
            field('last_name', 'Nachname', 'user.last_name', True),
            field('email', 'E-Mail-Adresse', 'user.email', True),
            field('phone', 'Telefonnummer', 'user.phone'),
            field('street', 'Straße und Hausnummer', 'master.street', True),
            field('postal_code', 'Postleitzahl', 'master.postal_code', True),
            field('city', 'Ort', 'master.city', True),
            field('birth_date', 'Geburtsdatum', 'master.birth_date', True, 'date'),
            field('nationality', 'Staatsangehörigkeit', 'master.nationality', True),
            field('birth_name', 'Geburtsname', 'master.birth_name'),
            field('birth_place', 'Geburtsort', 'master.birth_place'),
            field('birth_country', 'Geburtsland', 'master.birth_country'),
            field('social_insurance_number', 'Sozial-/Rentenversicherungsnummer', 'master.social_insurance_number'),
            field('health_insurance_name', 'Krankenkasse', 'master.health_insurance_name'),
            field('insurance_type', 'Versicherungsart', 'master.insurance_type', False, 'choice', ['gesetzlich', 'privat']),
            field('has_children', 'Kinder vorhanden', 'master.has_children', False, 'boolean'),
            field('children_under_25', 'Kinder unter 25', 'master.children_under_25', False, 'number'),
            field('tax_identification_number', 'Steueridentifikationsnummer', 'master.tax_identification_number'),
            field('tax_class', 'Steuerklasse/Faktor', 'master.tax_class'),
            field('tax_allowance', 'Freibeträge', 'master.tax_allowance'),
            field('child_allowance', 'Kinderfreibetrag', 'master.child_allowance'),
            field('religion', 'Konfession', 'master.religion'),
            field('spouse_religion', 'Konfession Ehepartner', 'master.spouse_religion'),
            field('iban', 'IBAN', 'master.iban', True),
            field('bank_account_holder', 'Kontoinhaber', 'master.bank_account_holder'),
            field('bank_name', 'Kreditinstitut', 'master.bank_name'),
            field('other_employments', 'Weitere Beschäftigungen', 'master.other_employments', False, 'list'),
            field('place', 'Ort', 'master.signature_place'),
            field('date', 'Datum', 'today', True, 'date'),
        ],
        'overlay': {'page': 0, 'font_size': 8, 'coordinates': {}},
    },
    {
        'slug': 'personalfragebogen-minijob',
        'name': 'Personalfragebogen Minijobber inkl. Rentenbefreiung',
        'kind': 'minijob_personnel',
        'audience': 'worker',
        'version': '06.2025',
        'source_format': 'pdf_overlay',
        'source_name': 'Personalfragebogen MJ Muster .pdf',
        'requires_signature': True,
        'signature_roles': ['employee', 'employer'],
        'fields': [
            field('salutation', 'Anrede', 'master.salutation'),
            field('first_name', 'Vorname', 'user.first_name', True),
            field('last_name', 'Nachname', 'user.last_name', True),
            field('email', 'E-Mail-Adresse', 'user.email', True),
            field('phone', 'Telefonnummer', 'user.phone'),
            field('street', 'Straße und Hausnummer', 'master.street', True),
            field('postal_code', 'Postleitzahl', 'master.postal_code', True),
            field('city', 'Ort', 'master.city', True),
            field('birth_date', 'Geburtsdatum', 'master.birth_date', True, 'date'),
            field('nationality', 'Staatsangehörigkeit', 'master.nationality', True),
            field('birth_name', 'Geburtsname', 'master.birth_name'),
            field('birth_place', 'Geburtsort', 'master.birth_place'),
            field('birth_country', 'Geburtsland', 'master.birth_country'),
            field('social_insurance_number', 'Sozial-/Rentenversicherungsnummer', 'master.social_insurance_number'),
            field('health_insurance_name', 'Krankenkasse', 'master.health_insurance_name'),
            field('insurance_type', 'Versicherungsart', 'master.insurance_type', False, 'choice', ['gesetzlich', 'privat']),
            field('tax_identification_number', 'Steueridentifikationsnummer', 'master.tax_identification_number'),
            field('iban', 'IBAN', 'master.iban', True),
            field('bank_account_holder', 'Kontoinhaber', 'master.bank_account_holder'),
            field('bank_name', 'Kreditinstitut', 'master.bank_name'),
            field('other_employments', 'Weitere Beschäftigungen', 'master.other_employments', False, 'list'),
            field('pension_exemption_requested', 'Befreiung Rentenversicherungspflicht beantragt', 'master.pension_exemption_requested', False, 'boolean'),
            field('employer_company_name', 'Arbeitgeber', 'company.name', True),
            field('employer_business_number', 'Betriebsnummer', 'company.business_number'),
            field('request_received_on', 'Eingang Befreiungsantrag', 'contract.variables.request_received_on', False, 'date'),
            field('exemption_effective_on', 'Befreiung wirksam ab', 'contract.variables.exemption_effective_on', False, 'date'),
            field('date', 'Datum', 'today', True, 'date'),
        ],
        'overlay': {'font_size': 8, 'coordinates': {}},
    },
    {
        'slug': 'arbeitsvertrag-dgb-gvp',
        'name': 'Arbeitsvertrag DGB/GVP',
        'kind': 'employment',
        'audience': 'worker',
        'version': '11.2025',
        'source_format': 'docx',
        'source_name': 'AV Muster 20262027.docx',
        'requires_signature': True,
        'signature_roles': ['employee', 'employer'],
        'fields': [
            field('company_name', 'Firma', 'company.name', True),
            field('company_address', 'Firmenanschrift', 'company.address', True),
            field('employee_name', 'Mitarbeiter', 'worker.full_name', True),
            field('employee_address', 'Anschrift Mitarbeiter', 'master.full_address', True),
            field('aueg_license_authority', 'Erlaubnisbehörde', 'company.aueg_license_authority', True),
            field('aueg_license_date', 'Datum AÜG-Erlaubnis', 'company.aueg_license_date', True, 'date'),
            field('einsatzbereich', '1b Einsatzbereich', 'contract.variables.einsatzbereich', True),
            field('start_date', 'Vertragsbeginn', 'contract.starts_on', True, 'date'),
            field('end_date', 'Vertragsende', 'contract.ends_on', False, 'date'),
            field('neuanstellung', 'Neuanstellung', 'contract.variables.neuanstellung', False, 'boolean'),
            field('taetigkeit', 'Tätigkeit', 'contract.variables.taetigkeit', True),
            field('pay_group', 'Entgeltgruppe', 'contract.variables.pay_group', True),
            field('employment_type', 'Beschäftigungsart', 'worker.employment_type', True),
            field('monthly_hours', 'Monatsstunden', 'worker.monthly_hours', True, 'number'),
            field('tariff_hourly_rate', 'Tariflicher Stundenlohn', 'worker.tariff_hourly_rate', True, 'money'),
            field('extra_allowance', 'Übertarifliche Zulage', 'worker.extra_allowance', False, 'money'),
            field('additional_agreements', 'Zusätzliche Vereinbarungen', 'contract.variables.additional_agreements'),
            field('signature_place', 'Ort', 'master.signature_place'),
            field('signature_date', 'Datum', 'today', True, 'date'),
        ],
    },
    {
        'slug': 'aufhebungsvertrag',
        'name': 'Aufhebungsvertrag',
        'kind': 'termination',
        'audience': 'worker',
        'version': '1.0',
        'source_format': 'docx',
        'source_name': 'Aufhebungsvertrag - Muster.docx',
        'requires_signature': True,
        'signature_roles': ['employee', 'employer'],
        'fields': [
            field('company_name', 'Arbeitgeber', 'company.name', True),
            field('company_address', 'Anschrift Arbeitgeber', 'company.address', True),
            field('employee_name', 'Arbeitnehmer', 'worker.full_name', True),
            field('employee_address', 'Anschrift Arbeitnehmer', 'master.full_address'),
            field('termination_date', 'Beendigungsdatum', 'contract.ends_on', True, 'date'),
            field('release_from_work', 'Arbeitsfreistellung', 'contract.variables.release_from_work', False, 'boolean'),
            field('remaining_leave_days', 'Resturlaubstage', 'contract.variables.remaining_leave_days', False, 'number'),
            field('signature_place', 'Ort', 'master.signature_place'),
            field('signature_date', 'Datum', 'today', True, 'date'),
        ],
    },
    {
        'slug': 'merkblatt-leiharbeitnehmer',
        'name': 'Merkblatt für Leiharbeitnehmerinnen und Leiharbeitnehmer',
        'kind': 'aueg_leaflet',
        'audience': 'worker',
        'version': '03.2023',
        'source_format': 'static_pdf',
        'source_name': '3. Merkblatt AN.pdf',
        'requires_signature': False,
        'signature_roles': [],
        'fields': [],
    },
    {
        'slug': 'verpflichtung-datengeheimnis',
        'name': 'Verpflichtung auf das Datengeheimnis',
        'kind': 'data_secrecy',
        'audience': 'worker',
        'version': '22.05.2018',
        'source_format': 'pdf_overlay',
        'source_name': '1. Datengeheimnis.pdf',
        'requires_signature': True,
        'signature_roles': ['employee'],
        'fields': [
            field('employee_name', 'Mitarbeiter', 'worker.full_name', True),
            field('signature_place', 'Ort', 'master.signature_place'),
            field('signature_date', 'Datum', 'today', True, 'date'),
        ],
        'overlay': {'page': 0, 'font_size': 9, 'coordinates': {}},
    },
    {
        'slug': 'zusatzvereinbarung-entgelt',
        'name': 'Zusatzvereinbarung – Vergütung nach tatsächlich geleisteten Stunden',
        'kind': 'pay_addendum',
        'audience': 'worker',
        'version': '1.0',
        'source_format': 'docx',
        'source_name': '2. Zusatzvereinbarung - Entgelt .docx',
        'requires_signature': True,
        'signature_roles': ['employee', 'employer'],
        'fields': [
            field('company_name', 'Arbeitgeber', 'company.name', True),
            field('company_address', 'Anschrift Arbeitgeber', 'company.address', True),
            field('employee_name', 'Arbeitnehmer', 'worker.full_name', True),
            field('monthly_hours', 'Regelmäßige Monatsstunden', 'worker.monthly_hours', True, 'number'),
            field('signature_place', 'Ort', 'master.signature_place'),
            field('signature_date', 'Datum', 'today', True, 'date'),
        ],
    },
    {
        'slug': 'wiederaufnahme-arbeitsverhaeltnis',
        'name': 'Vereinbarung zur Wiederaufnahme eines beendeten Arbeitsverhältnisses',
        'kind': 'rehire',
        'audience': 'worker',
        'version': '1.0',
        'source_format': 'docx',
        'source_name': 'Wiederaufnahme - Muster .docx',
        'requires_signature': True,
        'signature_roles': ['employee', 'employer'],
        'fields': [
            field('company_name', 'Arbeitgeber', 'company.name', True),
            field('company_address', 'Anschrift Arbeitgeber', 'company.address', True),
            field('employee_name', 'Arbeitnehmer', 'worker.full_name', True),
            field('original_contract_date', 'Datum ursprünglicher Vertrag', 'contract.variables.original_contract_date', True, 'date'),
            field('termination_agreement_date', 'Datum Aufhebungsvertrag', 'contract.variables.termination_agreement_date', True, 'date'),
            field('previous_end_date', 'Vorheriges Ende', 'contract.variables.previous_end_date', True, 'date'),
            field('rehire_date', 'Wiederaufnahme ab', 'contract.starts_on', True, 'date'),
            field('employment_type', 'Beschäftigungsart', 'worker.employment_type', True),
            field('pension_exemption_requested', 'Befreiung Rentenversicherung', 'master.pension_exemption_requested', False, 'boolean'),
            field('other_employments_confirmed', 'Keine schädlichen weiteren Beschäftigungen', 'contract.variables.other_employments_confirmed', False, 'boolean'),
            field('signature_place', 'Ort', 'master.signature_place'),
            field('signature_date', 'Datum', 'today', True, 'date'),
        ],
    },
]

CATALOG_BY_SLUG = {item['slug']: item for item in DOCUMENT_CATALOG}

WIW_SUPPORTED_MASTER_FIELDS = {
    'first_name', 'last_name', 'email', 'phone', 'employee_number', 'employment_type',
    'tariff_hourly_rate', 'street', 'postal_code', 'city',
}

WIW_UNSUPPORTED_LEGAL_FIELDS = {
    'birth_date', 'birth_name', 'birth_place', 'birth_country', 'nationality',
    'social_insurance_number', 'health_insurance_name', 'insurance_type',
    'tax_identification_number', 'tax_class', 'tax_allowance', 'child_allowance',
    'religion', 'spouse_religion', 'iban', 'bank_account_holder', 'bank_name',
    'pension_exemption_requested', 'signature_place', 'other_employments',
}
