from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView
from . import admin_center_views, advanced_views, akten_views, attendance_actions, attendance_views, automation_views, client_order_planning, client_portal_views, contract_views, document_catalog_views, document_center_views, global_search_views, integration_views, live_admin_center, live_operations, native_operations, oauth_views, payroll_views, portal_views, push_views, searchable_views, shift_views, store_review_views, time_views, views, worker_portal_views

router = DefaultRouter()
for prefix, view in [
    ('users', views.UserViewSet),
    ('clients', searchable_views.ClientCompanyViewSet),
    ('workers', searchable_views.WorkerViewSet),
    ('locations', views.LocationViewSet),
    ('positions', views.PositionViewSet),
    ('orders', searchable_views.OrderViewSet),
    ('availabilities', views.AvailabilityViewSet),
    ('shifts', shift_views.StaffingShiftViewSet),
    ('time-entries', time_views.TimeEntryViewSet),
    ('time-off', views.TimeOffViewSet),
    ('shift-swaps', views.ShiftSwapViewSet),
    ('contract-templates', views.ContractTemplateViewSet),
    ('contracts', contract_views.ContractViewSet),
    ('documents', searchable_views.DocumentViewSet),
    ('payroll', payroll_views.PayrollViewSet),
    ('ratings', client_portal_views.ClientSafeRatingViewSet),
    ('conversations', views.ConversationViewSet),
]:
    router.register(prefix, view)
router.register('notifications', views.NotificationViewSet, basename='notification')

urlpatterns = [
    path('auth/login/', views.login),
    path('auth/store-review/sync/', store_review_views.sync_store_review_credential),
    path('auth/refresh/', TokenRefreshView.as_view()),
    path('auth/me/', views.me),
    path('auth/change-password/', views.change_password),
    path('auth/account-deletion/', views.request_account_deletion),
    path('auth/oauth/<str:provider>/start/', oauth_views.oauth_start),
    path('auth/oauth/<str:provider>/callback/', oauth_views.oauth_callback),
    path('auth/activation/validate/', portal_views.activation_validate),
    path('auth/activation/complete/', portal_views.activation_complete),
    path('employee/home/', portal_views.employee_home),
    path('portal/message-recipients/', worker_portal_views.message_recipients),
    path('portal/rating-candidates/', client_portal_views.client_rating_candidates),
    path('employee/ranking/', worker_portal_views.employee_ranking),
    path('push/devices/register/', push_views.register_push_device),
    path('push/devices/unregister/', push_views.unregister_push_device),
    path('push/status/', push_views.push_status),
    path('admin/exceptions/', live_admin_center.admin_exception_center),
    path('search/global/', global_search_views.global_search),
    path('document-center/', document_center_views.document_center),
    path('document-center/templates/<slug:slug>/source/', document_center_views.upload_template_source),
    path('document-center/reminders/run/', document_center_views.run_contract_reminders),
    path('contracts/<uuid:pk>/readiness/', document_center_views.contract_readiness_view),
    path('attendance/home/', attendance_views.employee_attendance_home),
    path('attendance/entries/<uuid:entry_id>/correction/', attendance_views.request_time_correction),
    path('attendance/entries/<uuid:pk>/close/', attendance_actions.close_running_entry),
    path('attendance/corrections/<uuid:pk>/cancel/', attendance_views.cancel_time_correction),
    path('attendance/corrections/<uuid:pk>/decide/', attendance_views.decide_time_correction),
    path('attendance/exceptions/', attendance_views.attendance_exceptions),
    path('workers/portal-status/', portal_views.portal_statuses),
    path('workers/<uuid:pk>/invite/', portal_views.invite_worker),
    path('workers/<uuid:pk>/akte/', akten_views.worker_akte),
    path('workers/bulk-invite/', portal_views.bulk_invite_workers),
    path('clients/<uuid:pk>/akte/', akten_views.client_akte),
    path('orders/<uuid:pk>/confirm-and-plan/', client_order_planning.confirm_and_plan_order),
    path('setup/demo/', views.setup_demo),
    path('dashboard/', views.dashboard),
    path('integrations/wiw/status/', integration_views.wiw_status),
    path('integrations/wiw/discover/', integration_views.wiw_discover),
    path('integrations/wiw/sync/', integration_views.wiw_sync),
    path('integrations/wiw/webhook/', integration_views.wiw_webhook),
    path('workers/<uuid:pk>/master-data/', integration_views.worker_master_data),
    path('workers/<uuid:pk>/master-data/verify/', integration_views.verify_worker_master_data),
    path('document-catalog/', document_catalog_views.document_catalog),
    path('document-catalog/seed/', integration_views.seed_catalog),
    path('document-catalog/import-bundle/', integration_views.import_bundle),
    path('operations/', live_operations.operations_overview),
    path('operations/schedule-quality/', native_operations.schedule_quality),
    path('operations/availability/', advanced_views.availability_create),
    path('operations/availability/<uuid:pk>/', advanced_views.availability_delete),
    path('operations/swaps/', native_operations.swap_create),
    path('operations/swaps/<uuid:pk>/decide/', native_operations.swap_decide),
    path('operations/copy-week/', native_operations.copy_week),
    path('operations/bulk-publish/', native_operations.bulk_publish),
    path('operations/notifications/read-all/', advanced_views.notifications_read_all),
    path('operations/folders/', client_portal_views.folder_summary),
    path('operations/readiness/', advanced_views.readiness),
    path('operations/templates/import/', advanced_views.import_contract_templates),
    path('automation/orders/parse/', automation_views.order_parse),
    path('automation/orders/approve/', automation_views.order_approve),
    path('automation/orders/packages/', automation_views.order_packages),
    path('automation/orders/packages/<uuid:pk>/generate/', automation_views.order_generate),
    path('automation/orders/sync-packages/', automation_views.order_sync_packages),
    path('working-time/settings/', payroll_views.worktime_settings),
    path('working-time/sync/', automation_views.worktime_sync),
    path('working-time/records/', automation_views.worktime_records),
    path('working-time/records/<uuid:pk>/', automation_views.worktime_record_update),
    path('working-time/export/<str:file_format>/', automation_views.worktime_export),
    path('working-time/pdf/<uuid:worker_id>/', automation_views.worktime_pdf),
    path('working-time/backup/', automation_views.worktime_backup),
    path('reports/timesheets.csv', advanced_views.export_timesheets),
    path('reports/schedule.csv', native_operations.export_schedule),
    path('reports/payroll-estimate.csv', advanced_views.export_payroll_estimate),
    # Keep the DRF router last so fixed custom endpoints such as
    # workers/portal-status/ and workers/bulk-invite/ are not interpreted
    # as WorkerViewSet detail PKs.
    path('', include(router.urls)),
]
