import React, { useEffect, useMemo, useState } from 'react';
import { IonButton, IonInput, IonModal, IonSelect, IonSelectOption, IonSpinner, IonToast, IonToggle } from '@ionic/react';
import { api, apiAll } from './api';

const val=(e:any)=>e.detail.value??'';
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function defaultRange(){const now=new Date();const day=(now.getDay()+6)%7;const start=new Date(now);start.setDate(start.getDate()-day);const end=new Date(start);end.setDate(end.getDate()+7);return{start:dateKey(start),end:dateKey(end)}}

export default function ForecastToolsPanel({open,onClose,positions}:{open:boolean;onClose:()=>void;positions:any[]}){
  const initial=defaultRange();
  const [busy,setBusy]=useState(false),[toast,setToast]=useState(''),[schedules,setSchedules]=useState<any[]>([]),[schedule,setSchedule]=useState(''),[start,setStart]=useState(initial.start),[end,setEnd]=useState(initial.end),[summary,setSummary]=useState<any>(),[budgets,setBudgets]=useState<any[]>([]),[units,setUnits]=useState<any[]>([]);
  const [unitForm,setUnitForm]=useState<any>({name:'',unit_label:'Einheiten',mode:'hours',requirements:[]}),[selectedUnit,setSelectedUnit]=useState(''),[requirement,setRequirement]=useState<any>({units_basis:100,required_value:1});
  const [importFile,setImportFile]=useState<File>(),[preview,setPreview]=useState<any>(),[mapping,setMapping]=useState<any>({});

  async function bootstrap(){if(!open)return;const s=await apiAll('schedule-groups/?active=true');setSchedules(s);const id=schedule||s[0]?.id||'';setSchedule(id);if(id)await load(id);}
  useEffect(()=>{void bootstrap();},[open]);
  async function load(id=schedule){if(!id)return;setBusy(true);try{const [sum,b,u]=await Promise.all([api(`scheduling/forecast/?schedule=${id}&start=${start}&end=${end}`),apiAll(`forecast-days/?schedule=${id}&ordering=date`),apiAll(`forecast-units/?schedule=${id}&active=true`)]);setSummary(sum);setBudgets(b);setUnits(u);if(!selectedUnit&&u[0])setSelectedUnit(u[0].id);}catch(e:any){setToast(e.message);}finally{setBusy(false);}}
  useEffect(()=>{if(open&&schedule)void load(schedule);},[schedule,start,end]);

  const budgetMap=useMemo(()=>new Map(budgets.map(x=>[x.date,x])),[budgets]);
  const currentUnit=units.find(x=>x.id===selectedUnit);
  async function saveBudget(day:string,field:string,value:any){const existing=budgetMap.get(day)||{};const payload={schedule,date:day,sales_budget:existing.sales_budget||0,hours_budget:existing.hours_budget||0,labor_percent_target:existing.labor_percent_target||0,actual_sales:existing.actual_sales??null,[field]:value};try{await api('scheduling/forecast/budget/',{method:'POST',body:JSON.stringify(payload)});await load();}catch(e:any){setToast(e.message)}}
  async function saveUnitDay(definition:string,day:string,projected_units:any){try{await api('scheduling/forecast/unit-day/',{method:'POST',body:JSON.stringify({definition,date:day,projected_units})});await load();}catch(e:any){setToast(e.message)}}
  async function createUnit(){if(!schedule||!unitForm.name){setToast('Dienstplan und Name sind erforderlich.');return;}setBusy(true);try{const created:any=await api('forecast-units/',{method:'POST',body:JSON.stringify({...unitForm,schedule})});setSelectedUnit(created.id);setUnitForm({name:'',unit_label:'Einheiten',mode:'hours',requirements:[]});setToast('Custom Unit angelegt.');await load();}catch(e:any){setToast(e.message)}finally{setBusy(false)}}
  async function addRequirement(){if(!currentUnit||!requirement.position)return;const items=[...(currentUnit.requirements||[]).map((x:any)=>({position:x.position,units_basis:x.units_basis,required_value:x.required_value})),requirement];setBusy(true);try{await api(`forecast-units/${currentUnit.id}/`,{method:'PATCH',body:JSON.stringify({requirements:items})});setRequirement({units_basis:100,required_value:1});await load();}catch(e:any){setToast(e.message)}finally{setBusy(false)}}
  async function removeRequirement(positionId:string){if(!currentUnit)return;const items=(currentUnit.requirements||[]).filter((x:any)=>x.position!==positionId).map((x:any)=>({position:x.position,units_basis:x.units_basis,required_value:x.required_value}));try{await api(`forecast-units/${currentUnit.id}/`,{method:'PATCH',body:JSON.stringify({requirements:items})});await load();}catch(e:any){setToast(e.message)}}
  async function deleteUnit(){if(!currentUnit||!window.confirm('Custom Unit wirklich löschen?'))return;try{await api(`forecast-units/${currentUnit.id}/`,{method:'DELETE'});setSelectedUnit('');await load();}catch(e:any){setToast(e.message)}}

  async function previewImport(){if(!importFile)return;const data=new FormData();data.append('file',importFile);setBusy(true);try{const result:any=await api('scheduling/forecast/import/preview/',{method:'POST',body:data});setPreview(result);setMapping({});}catch(e:any){setToast(e.message)}finally{setBusy(false)}}
  async function applyImport(){if(!importFile||!mapping.date)return;const data=new FormData();data.append('file',importFile);data.append('schedule',schedule);data.append('mapping',JSON.stringify(mapping));setBusy(true);try{const result:any=await api('scheduling/forecast/import/apply/',{method:'POST',body:data});setToast(`${result.created} Tage erstellt, ${result.updated} aktualisiert, ${result.errors?.length||0} Fehler.`);setPreview(undefined);setImportFile(undefined);await load();}catch(e:any){setToast(e.message)}finally{setBusy(false)}}

  return <IonModal isOpen={open} onDidDismiss={onClose} className="forecast-modal"><div className="forecast-panel">
    <header className="forecast-head"><div><small>SCHEDULER · FORECAST TOOLS</small><h2>Labor & Bedarf planen</h2><p>Sales, Stundenbudget, Laborquote und eigene Forecast-Einheiten direkt gegen den Dienstplan.</p></div><IonButton fill="clear" onClick={onClose}>Schließen</IonButton></header>
    <div className="forecast-controls"><IonSelect fill="outline" label="Dienstplan" labelPlacement="floating" value={schedule} onIonChange={e=>setSchedule(String(val(e)))}>{schedules.map(s=><IonSelectOption key={s.id} value={s.id}>{s.name}</IonSelectOption>)}</IonSelect><IonInput fill="outline" type="date" label="Von" labelPlacement="floating" value={start} onIonInput={e=>setStart(String(val(e)))}/><IonInput fill="outline" type="date" label="Bis (exklusiv)" labelPlacement="floating" value={end} onIonInput={e=>setEnd(String(val(e)))}/><IonButton fill="outline" onClick={()=>void load()}>Aktualisieren</IonButton></div>
    {busy&&!summary?<div className="forecast-loading"><IonSpinner/></div>:summary?<>
      <section className="forecast-section"><div className="forecast-section-head"><div><h3>Sales & Hours Forecast</h3><p>Budgetwerte sind editierbar; geplante Stunden und Lohnkosten kommen live aus dem Scheduler.</p></div></div><div className="forecast-table-wrap"><table className="forecast-table"><thead><tr><th>Tag</th><th>Sales Budget</th><th>Actual Sales</th><th>Labor % Ziel</th><th>Labor Cost</th><th>Labor Var.</th><th>Hours Budget</th><th>Combined Hours</th><th>Hours Var.</th></tr></thead><tbody>{summary.days?.map((day:any)=>{const raw=budgetMap.get(day.date)||{};return <tr key={day.date}><td><b>{new Date(`${day.date}T12:00:00`).toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'})}</b></td><td><input type="number" step="0.01" defaultValue={raw.sales_budget||0} onBlur={e=>void saveBudget(day.date,'sales_budget',e.target.value)}/></td><td><input type="number" step="0.01" placeholder="–" defaultValue={raw.actual_sales??''} onBlur={e=>void saveBudget(day.date,'actual_sales',e.target.value)}/></td><td><input type="number" step="0.01" defaultValue={raw.labor_percent_target||0} onBlur={e=>void saveBudget(day.date,'labor_percent_target',e.target.value)}/></td><td>{day.assigned_labor_cost} € <small>({day.assigned_labor_percent}%)</small></td><td className={Number(day.labor_variance)<0?'negative':'positive'}>{day.labor_variance} €</td><td><input type="number" step="0.01" defaultValue={raw.hours_budget||0} onBlur={e=>void saveBudget(day.date,'hours_budget',e.target.value)}/></td><td>{day.combined_hours}</td><td className={Number(day.hours_variance)<0?'negative':'positive'}>{day.hours_variance}</td></tr>})}</tbody></table></div></section>

      <section className="forecast-section"><div className="forecast-section-head"><div><h3>Custom Unit Forecasting</h3><p>Zum Beispiel Gäste, Aufträge, Zimmer oder Tickets → benötigte Schichten oder Stunden je Position.</p></div></div><div className="forecast-unit-create"><IonInput fill="outline" label="Name" labelPlacement="floating" value={unitForm.name} onIonInput={e=>setUnitForm({...unitForm,name:val(e)})}/><IonInput fill="outline" label="Einheit (z. B. Gäste)" labelPlacement="floating" value={unitForm.unit_label} onIonInput={e=>setUnitForm({...unitForm,unit_label:val(e)})}/><IonSelect fill="outline" label="Berechnung" labelPlacement="floating" value={unitForm.mode} onIonChange={e=>setUnitForm({...unitForm,mode:val(e)})}><IonSelectOption value="hours">Stunden je Position</IonSelectOption><IonSelectOption value="shifts">Schichten je Position</IonSelectOption></IonSelect><IonButton onClick={()=>void createUnit()}>Custom Unit anlegen</IonButton></div>
        {!!units.length&&<><div className="forecast-unit-tabs">{units.map(u=><button className={selectedUnit===u.id?'active':''} key={u.id} onClick={()=>setSelectedUnit(u.id)}>{u.name}</button>)}</div>{currentUnit&&<div className="forecast-unit-editor"><div className="forecast-unit-title"><div><b>{currentUnit.name}</b><small>{currentUnit.unit_label} · {currentUnit.mode==='hours'?'Stunden':'Schichten'}</small></div><IonButton size="small" fill="clear" color="danger" onClick={()=>void deleteUnit()}>Löschen</IonButton></div><div className="forecast-requirements">{currentUnit.requirements?.map((r:any)=><div key={r.position}><span><b>{r.position_name}</b><small>je {r.units_basis} {currentUnit.unit_label} → {r.required_value} {currentUnit.mode==='hours'?'Std.':'Schicht(en)'}</small></span><IonButton size="small" fill="clear" color="danger" onClick={()=>void removeRequirement(r.position)}>×</IonButton></div>)}</div><div className="forecast-requirement-form"><IonSelect fill="outline" label="Position" labelPlacement="floating" value={requirement.position} onIonChange={e=>setRequirement({...requirement,position:val(e)})}>{positions.map(p=><IonSelectOption key={p.id} value={p.id}>{p.name}</IonSelectOption>)}</IonSelect><IonInput fill="outline" type="number" label={`Basis ${currentUnit.unit_label}`} labelPlacement="floating" value={requirement.units_basis} onIonInput={e=>setRequirement({...requirement,units_basis:val(e)})}/><IonInput fill="outline" type="number" label={currentUnit.mode==='hours'?'Benötigte Stunden':'Benötigte Schichten'} labelPlacement="floating" value={requirement.required_value} onIonInput={e=>setRequirement({...requirement,required_value:val(e)})}/><IonButton disabled={!requirement.position} onClick={()=>void addRequirement()}>Regel hinzufügen</IonButton></div><div className="forecast-table-wrap"><table className="forecast-table custom"><thead><tr><th>Tag</th><th>Projected {currentUnit.unit_label}</th>{currentUnit.requirements?.map((r:any)=><th key={r.position}>{r.position_name}</th>)}</tr></thead><tbody>{summary.days?.map((day:any)=>{const custom=day.custom_units?.find((x:any)=>x.definition===currentUnit.id);return <tr key={day.date}><td>{new Date(`${day.date}T12:00:00`).toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'})}</td><td><input type="number" step="0.01" defaultValue={custom?.projected_units||0} onBlur={e=>void saveUnitDay(currentUnit.id,day.date,e.target.value)}/></td>{currentUnit.requirements?.map((r:any)=>{const req=custom?.requirements?.find((x:any)=>x.position===r.position);return <td key={r.position}><b>{req?.scheduled||0}/{req?.required||0}</b><small className={Number(req?.variance||0)<0?'negative':'positive'}>{req?.variance||0}</small></td>})}</tr>})}</tbody></table></div></div>}</>}
      </section>

      <section className="forecast-section"><div className="forecast-section-head"><div><h3>Forecast-Daten importieren</h3><p>CSV, XLS oder XLSX bis 8 MB. Nach der Vorschau werden die Spalten bewusst zugeordnet.</p></div></div><div className="forecast-import"><input type="file" accept=".csv,.xls,.xlsx" onChange={e=>{setImportFile(e.target.files?.[0]);setPreview(undefined)}}/><IonButton fill="outline" disabled={!importFile||busy} onClick={()=>void previewImport()}>Datei prüfen</IonButton></div>{preview&&<><p><b>{preview.row_count}</b> Zeilen erkannt.</p><div className="forecast-mapping"><MapSelect label="Datum *" headers={preview.headers} value={mapping.date} set={(v:string)=>setMapping({...mapping,date:v})}/><MapSelect label="Sales Budget" headers={preview.headers} value={mapping.sales_budget} set={(v:string)=>setMapping({...mapping,sales_budget:v})}/><MapSelect label="Actual Sales" headers={preview.headers} value={mapping.actual_sales} set={(v:string)=>setMapping({...mapping,actual_sales:v})}/><MapSelect label="Hours Budget" headers={preview.headers} value={mapping.hours_budget} set={(v:string)=>setMapping({...mapping,hours_budget:v})}/><MapSelect label="Labor % Ziel" headers={preview.headers} value={mapping.labor_percent_target} set={(v:string)=>setMapping({...mapping,labor_percent_target:v})}/>{units.map(u=><MapSelect key={u.id} label={`Unit: ${u.name}`} headers={preview.headers} value={mapping[`unit:${u.id}`]} set={(v:string)=>setMapping({...mapping,[`unit:${u.id}`]:v})}/>)}</div><IonButton disabled={!mapping.date||busy} onClick={()=>void applyImport()}>Import ausführen</IonButton></>}
      </section>
    </>:<div className="forecast-empty">Dienstplan auswählen, um Forecast Tools zu verwenden.</div>}
    <IonToast isOpen={!!toast} message={toast} duration={4000} onDidDismiss={()=>setToast('')}/>
  </div></IonModal>
}

function MapSelect({label,headers,value,set}:{label:string;headers:string[];value?:string;set:(value:string)=>void}){return <IonSelect fill="outline" label={label} labelPlacement="floating" value={value||''} onIonChange={e=>set(String(val(e)||''))}><IonSelectOption value="">Nicht importieren</IonSelectOption>{headers.map(h=><IonSelectOption key={h} value={h}>{h}</IonSelectOption>)}</IonSelect>}
