import React, { useEffect, useMemo, useState } from 'react';
import {
  IonBadge, IonButton, IonCard, IonCardContent, IonInput, IonItem, IonLabel,
  IonSegment, IonSegmentButton, IonSelect, IonSelectOption, IonSpinner, IonTextarea, IonToggle,
} from '@ionic/react';
import { api, User } from './api';
import './premium-integrations.css';

type ApiKey = {id:string;name:string;prefix:string;scopes:string[];active:boolean;expires_at?:string|null;last_used_at?:string|null;revoked_at?:string|null};
type Webhook = {id:string;name:string;url:string;event_types:string[];active:boolean;timeout_seconds:number;max_attempts:number;last_success_at?:string|null;last_failure_at?:string|null};
type Delivery = {id:string;subscription:string;event_type:string;status:string;attempts:number;last_http_status?:number|null;last_error?:string;created_at:string};
type Saml = {id:string;name:string;enabled:boolean;sp_entity_id:string;idp_entity_id:string;sso_url:string;x509_certificate:string;allowed_domains:string[];auto_provision:boolean;default_role:string};
type Connector = {id:string;name:string;provider:string;configuration:any;active:boolean;has_credentials:boolean;last_export_at?:string|null};
type Period = {id:string;name:string;status:string;starts_on:string;ends_on:string};
type Tab = 'keys'|'webhooks'|'saml'|'payroll';

const API_BASE=(import.meta.env.VITE_API_URL||'http://localhost:8000/api').replace(/\/$/,'');
const WEBHOOK_EVENTS=['shift.created','shift.updated','time_entry.created','time_entry.updated','time_off.created','time_off.updated','pay_period.created','pay_period.updated','timesheet.created','timesheet.updated'];
const scopeLabels:Record<string,string>={'workers.read':'Mitarbeiter lesen','shifts.read':'Schichten lesen','timesheets.read':'Timesheets lesen','payroll.export':'Payroll exportieren','webhooks.write':'Webhooks verwalten'};
const val=(e:any)=>e.detail?.value ?? e.target?.value ?? '';

export default function PremiumIntegrationsPanel({user}:{user:User}){
  const eligible=user.role==='admin'||(user.capabilities||[]).includes('workplace.manage');
  const [tab,setTab]=useState<Tab>('keys');
  const [keys,setKeys]=useState<ApiKey[]>([]); const [scopes,setScopes]=useState<string[]>([]);
  const [hooks,setHooks]=useState<Webhook[]>([]); const [deliveries,setDeliveries]=useState<Delivery[]>([]);
  const [saml,setSaml]=useState<Saml[]>([]); const [connectors,setConnectors]=useState<Connector[]>([]); const [periods,setPeriods]=useState<Period[]>([]);
  const [loading,setLoading]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const [revealed,setRevealed]=useState<{title:string;value:string}|null>(null);
  const [keyForm,setKeyForm]=useState({name:'',scopes:['workers.read'] as string[],expires_at:''});
  const [hookForm,setHookForm]=useState({name:'',url:'',event_types:['shift.updated'] as string[],max_attempts:6,timeout_seconds:10});
  const [samlForm,setSamlForm]=useState({name:'Company SSO',enabled:false,sp_entity_id:'',idp_entity_id:'',sso_url:'',x509_certificate:'',allowed_domains:'',auto_provision:false,default_role:'worker'});
  const [payrollForm,setPayrollForm]=useState({name:'DATEV',provider:'datev_csv',url:'',bearer_token:''});
  const [selectedPeriod,setSelectedPeriod]=useState<Record<string,string>>({});

  async function load(){
    if(!eligible)return; setLoading(true);setError('');
    try{
      const [keyData,hookData,deliveryData,samlData,connectorData,periodData]:any[]=await Promise.all([
        api('integrations/api-keys/'),api('integrations/webhooks/'),api('integrations/webhook-deliveries/'),
        api('integrations/saml/providers/'),api('integrations/payroll/connectors/'),api('pay-periods/?page_size=100'),
      ]);
      setKeys(keyData.results||[]);setScopes(keyData.scopes||[]);setHooks(hookData.results||[]);setDeliveries(deliveryData.results||[]);
      setSaml(samlData.results||[]);setConnectors(connectorData.results||[]);setPeriods((periodData.results||periodData||[]).filter((x:Period)=>['closed','locked'].includes(x.status)));
    }catch(e:any){setError(e.message);}finally{setLoading(false);}
  }
  useEffect(()=>{void load();},[eligible]);
  const deadCount=useMemo(()=>deliveries.filter(x=>x.status==='dead').length,[deliveries]);
  if(!eligible)return null;

  async function createKey(){setBusy(true);setError('');try{const row:any=await api('integrations/api-keys/',{method:'POST',body:JSON.stringify({...keyForm,expires_at:keyForm.expires_at||null})});setRevealed({title:'API Key – nur jetzt kopieren',value:row.token});setKeyForm({name:'',scopes:['workers.read'],expires_at:''});setNotice('API Key erstellt.');await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function revokeKey(id:string){if(!confirm('API Key wirklich sperren?'))return;setBusy(true);try{await api(`integrations/api-keys/${id}/revoke/`,{method:'POST',body:'{}'});await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function createHook(){setBusy(true);setError('');try{const row:any=await api('integrations/webhooks/',{method:'POST',body:JSON.stringify(hookForm)});setRevealed({title:'Webhook Secret – nur jetzt kopieren',value:row.secret});setHookForm({name:'',url:'',event_types:['shift.updated'],max_attempts:6,timeout_seconds:10});await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function rotateHook(id:string){if(!confirm('Webhook Secret rotieren? Das alte Secret wird sofort ungültig.'))return;setBusy(true);try{const row:any=await api(`integrations/webhooks/${id}/rotate-secret/`,{method:'POST',body:'{}'});setRevealed({title:'Neues Webhook Secret – nur jetzt kopieren',value:row.secret});}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function testHook(id:string){setBusy(true);setError('');try{const row:any=await api(`integrations/webhooks/${id}/test/`,{method:'POST',body:'{}'});setNotice(`Testzustellung: ${row.status}${row.http_status?` · HTTP ${row.http_status}`:''}`);await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function createSaml(){setBusy(true);setError('');try{await api('integrations/saml/providers/',{method:'POST',body:JSON.stringify({...samlForm,allowed_domains:samlForm.allowed_domains.split(',').map(x=>x.trim()).filter(Boolean)})});setNotice('SAML Provider gespeichert.');await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function toggleSaml(row:Saml,enabled:boolean){setBusy(true);try{await api(`integrations/saml/providers/${row.id}/`,{method:'PATCH',body:JSON.stringify({enabled})});await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function createPayroll(){setBusy(true);setError('');try{const configuration=payrollForm.provider==='generic_json'?{url:payrollForm.url,timeout_seconds:20}:{};const credentials=payrollForm.bearer_token?{bearer_token:payrollForm.bearer_token}:{};await api('integrations/payroll/connectors/',{method:'POST',body:JSON.stringify({name:payrollForm.name,provider:payrollForm.provider,configuration,credentials})});setPayrollForm({name:'DATEV',provider:'datev_csv',url:'',bearer_token:''});setNotice('Payroll Connector erstellt.');await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function exportPayroll(connector:Connector){const period=selectedPeriod[connector.id];if(!period){setError('Bitte zuerst eine geschlossene Pay Period wählen.');return;}setBusy(true);setError('');try{const response=await fetch(`${API_BASE}/integrations/payroll/connectors/${connector.id}/export/${period}/`,{method:'POST',headers:{Authorization:`Bearer ${localStorage.getItem('access')||''}`,'Content-Type':'application/json'},body:'{}'});if(!response.ok){const body=await response.json().catch(()=>({detail:'Export fehlgeschlagen.'}));throw new Error(body.detail||'Export fehlgeschlagen.');}const type=response.headers.get('content-type')||'';if(type.includes('text/csv')){const blob=await response.blob();const disposition=response.headers.get('content-disposition')||'';const name=/filename="?([^";]+)"?/i.exec(disposition)?.[1]||'payroll.csv';const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);setNotice('Payroll-Datei erstellt.');}else{setNotice('Payroll-Export an Provider übertragen.');}await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}

  return <section className="premium-integrations" data-testid="premium-integrations-panel">
    <div className="pi-head"><div><small>ENTERPRISE</small><h3>Premium Integrationen</h3><p>API, Webhooks, SSO und Payroll zentral und nachvollziehbar verwalten.</p></div><div><IonBadge color="primary">{keys.filter(x=>x.active).length} API Keys</IonBadge>{deadCount>0&&<IonBadge color="danger">{deadCount} Dead Letter</IonBadge>}</div></div>
    {error&&<div className="pi-message error">{error}</div>}{notice&&<div className="pi-message success">{notice}</div>}
    {revealed&&<div className="pi-secret"><div><b>{revealed.title}</b><p>Nach dem Schließen wird dieser Wert nicht erneut angezeigt.</p><code>{revealed.value}</code></div><div><IonButton size="small" onClick={()=>navigator.clipboard?.writeText(revealed.value)}>Kopieren</IonButton><IonButton size="small" fill="outline" onClick={()=>setRevealed(null)}>Schließen</IonButton></div></div>}
    <IonSegment value={tab} onIonChange={e=>setTab(val(e) as Tab)}><IonSegmentButton value="keys">API Keys</IonSegmentButton><IonSegmentButton value="webhooks">Webhooks</IonSegmentButton><IonSegmentButton value="saml">SAML SSO</IonSegmentButton><IonSegmentButton value="payroll">Payroll</IonSegmentButton></IonSegment>
    {loading?<div className="pi-loading"><IonSpinner/><span>Integrationen werden geladen …</span></div>:<>
      {tab==='keys'&&<div className="pi-grid"><IonCard><IonCardContent><h4>Neuen API Key erstellen</h4><IonInput label="Name" labelPlacement="stacked" value={keyForm.name} onIonInput={e=>setKeyForm(x=>({...x,name:val(e)}))}/><IonSelect label="Scopes" labelPlacement="stacked" multiple value={keyForm.scopes} onIonChange={e=>setKeyForm(x=>({...x,scopes:val(e)}))}>{scopes.map(scope=><IonSelectOption key={scope} value={scope}>{scopeLabels[scope]||scope}</IonSelectOption>)}</IonSelect><IonInput type="datetime-local" label="Ablauf (optional)" labelPlacement="stacked" value={keyForm.expires_at} onIonInput={e=>setKeyForm(x=>({...x,expires_at:val(e)}))}/><IonButton disabled={busy||!keyForm.name||!keyForm.scopes.length} onClick={()=>void createKey()}>API Key erstellen</IonButton></IonCardContent></IonCard><div className="pi-list">{keys.map(row=><article key={row.id}><div><b>{row.name}</b><small>awf_{row.prefix}_•••• · {row.scopes.map(x=>scopeLabels[x]||x).join(', ')}</small></div><div>{row.active&&!row.revoked_at?<IonBadge color="success">Aktiv</IonBadge>:<IonBadge color="medium">Gesperrt</IonBadge>}{row.active&&!row.revoked_at&&<IonButton size="small" fill="outline" color="danger" onClick={()=>void revokeKey(row.id)}>Sperren</IonButton>}</div></article>)}</div></div>}
      {tab==='webhooks'&&<div className="pi-grid"><IonCard><IonCardContent><h4>Webhook Endpoint</h4><IonInput label="Name" labelPlacement="stacked" value={hookForm.name} onIonInput={e=>setHookForm(x=>({...x,name:val(e)}))}/><IonInput label="HTTPS URL" labelPlacement="stacked" value={hookForm.url} onIonInput={e=>setHookForm(x=>({...x,url:val(e)}))}/><IonSelect label="Events" labelPlacement="stacked" multiple value={hookForm.event_types} onIonChange={e=>setHookForm(x=>({...x,event_types:val(e)}))}><IonSelectOption value="*">Alle Events</IonSelectOption>{WEBHOOK_EVENTS.map(x=><IonSelectOption key={x} value={x}>{x}</IonSelectOption>)}</IonSelect><IonButton disabled={busy||!hookForm.name||!hookForm.url} onClick={()=>void createHook()}>Webhook erstellen</IonButton></IonCardContent></IonCard><div><div className="pi-list">{hooks.map(row=><article key={row.id}><div><b>{row.name}</b><small>{row.url}<br/>{row.event_types.join(', ')}</small></div><div><IonBadge color={row.active?'success':'medium'}>{row.active?'Aktiv':'Inaktiv'}</IonBadge><IonButton size="small" fill="outline" onClick={()=>void testHook(row.id)}>Test</IonButton><IonButton size="small" fill="outline" onClick={()=>void rotateHook(row.id)}>Secret rotieren</IonButton></div></article>)}</div><h4>Letzte Zustellungen</h4><div className="pi-deliveries">{deliveries.slice(0,20).map(row=><div key={row.id}><span><b>{row.event_type}</b><small>{row.subscription} · {row.attempts} Versuch(e)</small></span><IonBadge color={row.status==='delivered'?'success':row.status==='dead'?'danger':'warning'}>{row.status}</IonBadge></div>)}</div></div></div>}
      {tab==='saml'&&<div className="pi-grid"><IonCard><IonCardContent><h4>SAML v2 Identity Provider</h4><IonInput label="Name" labelPlacement="stacked" value={samlForm.name} onIonInput={e=>setSamlForm(x=>({...x,name:val(e)}))}/><IonInput label="IdP Entity ID" labelPlacement="stacked" value={samlForm.idp_entity_id} onIonInput={e=>setSamlForm(x=>({...x,idp_entity_id:val(e)}))}/><IonInput label="SSO URL" labelPlacement="stacked" value={samlForm.sso_url} onIonInput={e=>setSamlForm(x=>({...x,sso_url:val(e)}))}/><IonInput label="SP Entity ID (optional)" labelPlacement="stacked" value={samlForm.sp_entity_id} onIonInput={e=>setSamlForm(x=>({...x,sp_entity_id:val(e)}))}/><IonInput label="Erlaubte E-Mail-Domains" labelPlacement="stacked" placeholder="firma.de, partner.de" value={samlForm.allowed_domains} onIonInput={e=>setSamlForm(x=>({...x,allowed_domains:val(e)}))}/><IonTextarea label="X.509 Zertifikat (PEM)" labelPlacement="stacked" autoGrow value={samlForm.x509_certificate} onIonInput={e=>setSamlForm(x=>({...x,x509_certificate:val(e)}))}/><IonItem lines="none"><IonToggle checked={samlForm.auto_provision} onIonChange={e=>setSamlForm(x=>({...x,auto_provision:e.detail.checked}))}>Benutzer automatisch anlegen</IonToggle></IonItem><IonSelect label="Standardrolle" labelPlacement="stacked" value={samlForm.default_role} onIonChange={e=>setSamlForm(x=>({...x,default_role:val(e)}))}><IonSelectOption value="worker">Mitarbeiter</IonSelectOption><IonSelectOption value="manager">Manager</IonSelectOption><IonSelectOption value="client">Kunde</IonSelectOption></IonSelect><IonButton disabled={busy||!samlForm.idp_entity_id||!samlForm.sso_url||!samlForm.x509_certificate} onClick={()=>void createSaml()}>SSO Provider speichern</IonButton></IonCardContent></IonCard><div className="pi-list">{saml.map(row=><article key={row.id}><div><b>{row.name}</b><small>{row.idp_entity_id}<br/>{row.allowed_domains.length?row.allowed_domains.join(', '):'Alle Domains'} · Auto-Provision {row.auto_provision?'an':'aus'}</small></div><div><IonToggle checked={row.enabled} disabled={busy} onIonChange={e=>void toggleSaml(row,e.detail.checked)}>Aktiv</IonToggle></div></article>)}</div></div>}
      {tab==='payroll'&&<div className="pi-grid"><IonCard><IonCardContent><h4>Payroll Connector</h4><IonInput label="Name" labelPlacement="stacked" value={payrollForm.name} onIonInput={e=>setPayrollForm(x=>({...x,name:val(e)}))}/><IonSelect label="Provider" labelPlacement="stacked" value={payrollForm.provider} onIonChange={e=>setPayrollForm(x=>({...x,provider:val(e)}))}><IonSelectOption value="datev_csv">DATEV CSV</IonSelectOption><IonSelectOption value="generic_json">Generic JSON API</IonSelectOption></IonSelect>{payrollForm.provider==='generic_json'&&<><IonInput label="HTTPS Endpoint" labelPlacement="stacked" value={payrollForm.url} onIonInput={e=>setPayrollForm(x=>({...x,url:val(e)}))}/><IonInput type="password" label="Bearer Token (optional)" labelPlacement="stacked" value={payrollForm.bearer_token} onIonInput={e=>setPayrollForm(x=>({...x,bearer_token:val(e)}))}/></>}<IonButton disabled={busy||!payrollForm.name||(payrollForm.provider==='generic_json'&&!payrollForm.url)} onClick={()=>void createPayroll()}>Connector erstellen</IonButton></IonCardContent></IonCard><div className="pi-list">{connectors.map(row=><article key={row.id}><div><b>{row.name}</b><small>{row.provider==='datev_csv'?'DATEV CSV':'Generic JSON API'} · Credentials {row.has_credentials?'hinterlegt':'keine'}</small></div><div className="pi-export"><IonSelect interface="popover" placeholder="Pay Period" value={selectedPeriod[row.id]||''} onIonChange={e=>setSelectedPeriod(x=>({...x,[row.id]:val(e)}))}>{periods.map(p=><IonSelectOption key={p.id} value={p.id}>{p.name} · {p.status}</IonSelectOption>)}</IonSelect><IonButton size="small" disabled={busy||!selectedPeriod[row.id]} onClick={()=>void exportPayroll(row)}>Export</IonButton></div></article>)}</div></div>}
    </>}
  </section>;
}
