import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('core', '0007_seed_store_reviewer')]

    operations = [
        migrations.CreateModel(name='SchedulingPolicy', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('name', models.CharField(default='Standard', max_length=120)), ('active', models.BooleanField(default=True)),
            ('min_hours_same_day', models.DecimalField(decimal_places=1, default=0, max_digits=4)), ('min_hours_between_days', models.DecimalField(decimal_places=1, default=11, max_digits=4)),
            ('max_days_in_row', models.PositiveSmallIntegerField(default=6)), ('max_days_per_week', models.PositiveSmallIntegerField(default=6)), ('max_hours_per_day', models.DecimalField(decimal_places=1, default=10, max_digits=4)), ('max_hours_per_week', models.DecimalField(decimal_places=1, default=48, max_digits=5)),
            ('respect_worker_monthly_hours', models.BooleanField(default=True)), ('allow_multiple_shifts_per_day', models.BooleanField(default=False)), ('allow_overlapping_open_shifts', models.BooleanField(default=True)), ('labor_sharing_enabled', models.BooleanField(default=True)), ('task_lists_enabled', models.BooleanField(default=True)), ('auto_schedule_enabled', models.BooleanField(default=True)), ('pickup_approval_required', models.BooleanField(default=False)), ('weekend_first', models.BooleanField(default=True)), ('timezone_toggle_enabled', models.BooleanField(default=True)), ('default_timezone', models.CharField(default='Europe/Berlin', max_length=64)),
        ], options={'ordering': ['-active', 'name']}),
        migrations.CreateModel(name='ShiftTag', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=80, unique=True)), ('color', models.CharField(default='#2457E6', max_length=20)), ('active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='ScheduleTemplate', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=160)), ('active', models.BooleanField(default=True)),
            ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_templates_created', to=settings.AUTH_USER_MODEL)), ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_templates', to='core.location')),
        ]),
        migrations.CreateModel(name='TaskList', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=160)), ('kind', models.CharField(choices=[('team','Team-Aufgaben'),('shift','Schicht-Aufgaben')], default='shift', max_length=20)), ('active', models.BooleanField(default=True)),
            ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_lists_created', to=settings.AUTH_USER_MODEL)), ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_lists', to='core.location')),
        ]),
        migrations.CreateModel(name='ForecastMetric', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120, unique=True)), ('unit', models.CharField(default='Einheit', max_length=40)), ('active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='TimeOffCategory', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=100, unique=True)), ('code', models.SlugField(max_length=50, unique=True)), ('paid', models.BooleanField(default=False)), ('requires_approval', models.BooleanField(default=True)), ('active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='ReportDefinition', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=160)), ('kind', models.CharField(choices=[('shifts','Schichten'),('times','Zeiten'),('shift_history','Schichtverlauf'),('users','Mitarbeiter'),('time_off','Abwesenheiten'),('labor','Personalkosten')], max_length=30)), ('columns', models.JSONField(default=list)), ('filters', models.JSONField(blank=True, default=dict)), ('sorting', models.JSONField(blank=True, default=list)), ('shared', models.BooleanField(default=False)), ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_definitions', to=settings.AUTH_USER_MODEL)),
        ], options={'ordering':['name']}),
        migrations.CreateModel(name='PublicApiKey', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120)), ('prefix', models.CharField(max_length=16, unique=True)), ('key_hash', models.CharField(max_length=64)), ('scopes', models.JSONField(default=list)), ('active', models.BooleanField(default=True)), ('expires_at', models.DateTimeField(blank=True, null=True)), ('last_used_at', models.DateTimeField(blank=True, null=True)), ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_api_keys', to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name='WebhookSubscription', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120)), ('endpoint_url', models.URLField(max_length=500)), ('signing_secret', models.CharField(max_length=128)), ('events', models.JSONField(default=list)), ('active', models.BooleanField(default=True)), ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name='SamlIdentity', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('idp_entity_id', models.CharField(max_length=500)), ('name_id', models.CharField(max_length=500)), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saml_identities', to=settings.AUTH_USER_MODEL)),
        ], options={'unique_together':{('idp_entity_id','name_id')}}),
        migrations.CreateModel(name='ExternalIntegration', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120)), ('kind', models.CharField(choices=[('payroll','Payroll'),('pos','POS'),('generic','Generisch')], max_length=20)), ('provider', models.CharField(max_length=80)), ('endpoint_url', models.URLField(blank=True, max_length=500)), ('credential_env', models.JSONField(blank=True, default=dict)), ('config', models.JSONField(blank=True, default=dict)), ('active', models.BooleanField(default=True)), ('last_sync_at', models.DateTimeField(blank=True, null=True)), ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_integrations', to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name='ShiftTagLink', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_tag_links', to='core.shift')), ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_links', to='core.shifttag')),
        ], options={'unique_together':{('shift','tag')}}),
        migrations.CreateModel(name='ScheduleTemplateShift', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('weekday', models.PositiveSmallIntegerField()), ('start_time', models.TimeField()), ('end_time', models.TimeField()), ('break_minutes', models.PositiveIntegerField(default=0)), ('required_count', models.PositiveIntegerField(default=1)), ('notes', models.TextField(blank=True)), ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_template_items', to='core.position')), ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.scheduletemplate')),
        ], options={'ordering':['weekday','start_time']}),
        migrations.CreateModel(name='TaskItem', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('title', models.CharField(max_length=220)), ('description', models.TextField(blank=True)), ('required', models.BooleanField(default=True)), ('sort_order', models.PositiveIntegerField(default=0)), ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.tasklist')),
        ], options={'ordering':['sort_order','created_at']}),
        migrations.CreateModel(name='TaskRun', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('run_date', models.DateField()), ('closed_at', models.DateTimeField(blank=True, null=True)), ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_runs', to='core.workerprofile')), ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='core.location')), ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='core.shift')), ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='core.tasklist')),
        ], options={'ordering':['-run_date','created_at']}),
        migrations.CreateModel(name='TaskCompletion', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('completed_at', models.DateTimeField(default=django.utils.timezone.now)), ('note', models.TextField(blank=True)), ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_completions', to=settings.AUTH_USER_MODEL)), ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.taskitem')), ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.taskrun')),
        ], options={'unique_together':{('run','item')}}),
        migrations.CreateModel(name='DailyForecast', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('date', models.DateField()), ('projected_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('projected_units', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('labor_budget_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)), ('labor_budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('notes', models.TextField(blank=True)), ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.location')), ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_values', to='core.forecastmetric')),
        ], options={'ordering':['date','location__name'],'unique_together':{('location','date','metric')}}),
        migrations.CreateModel(name='StaffCallout', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('reason', models.TextField(blank=True)), ('status', models.CharField(choices=[('open','Offen'),('covered','Abgedeckt'),('closed','Geschlossen')], default='open', max_length=20)), ('resolved_at', models.DateTimeField(blank=True, null=True)), ('covered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_callouts', to='core.workerprofile')), ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_callouts', to=settings.AUTH_USER_MODEL)), ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callouts', to='core.shift')), ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callouts', to='core.shiftslot')), ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callouts', to='core.workerprofile')),
        ], options={'ordering':['-created_at']}),
        migrations.CreateModel(name='TimeOffClassification', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='core.timeoffcategory')), ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='core.timeoffrequest')),
        ]),
        migrations.CreateModel(name='WebhookDelivery', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('event_type', models.CharField(max_length=120)), ('payload', models.JSONField(default=dict)), ('status', models.CharField(choices=[('pending','Ausstehend'),('delivered','Zugestellt'),('failed','Fehlgeschlagen')], default='pending', max_length=20)), ('attempts', models.PositiveIntegerField(default=0)), ('response_status', models.PositiveIntegerField(blank=True, null=True)), ('response_body', models.TextField(blank=True)), ('next_attempt_at', models.DateTimeField(blank=True, null=True)), ('delivered_at', models.DateTimeField(blank=True, null=True)), ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.webhooksubscription')),
        ], options={'ordering':['-created_at']}),
    ]
