import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_policy(apps, schema_editor):
    Policy = apps.get_model('core', 'AttendancePolicy')
    Policy.objects.get_or_create(
        name='Standard – A+ Workforce',
        location=None,
        defaults={
            'active': True,
            'priority': 0,
            'early_clock_in_minutes': 15,
            'early_clock_in_mode': 'off',
            'late_clock_in_grace_minutes': 5,
            'early_clock_out_grace_minutes': 5,
            'late_clock_out_grace_minutes': 15,
            'no_show_after_minutes': 30,
            'missed_clock_out_after_minutes': 120,
            'clock_in_location_mode': 'block',
            'clock_out_location_mode': 'block',
            'allow_unscheduled_clock_in': False,
            'required_break_after_minutes': 360,
            'required_break_minutes': 30,
            'default_break_paid': False,
            'auto_deduct_unpaid_breaks': False,
            'break_attestation_required': False,
            'end_of_shift_attestation_required': False,
            'terminal_photo_clock_in': False,
            'terminal_photo_clock_out': False,
        },
    )


class Migration(migrations.Migration):
    dependencies = [('core', '0010_absence_coverage')]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Standard', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('early_clock_in_minutes', models.PositiveIntegerField(default=15)),
                ('early_clock_in_mode', models.CharField(choices=[('off', 'Aus'), ('warn', 'Hinweis'), ('block', 'Blockieren')], default='off', max_length=10)),
                ('late_clock_in_grace_minutes', models.PositiveIntegerField(default=5)),
                ('early_clock_out_grace_minutes', models.PositiveIntegerField(default=5)),
                ('late_clock_out_grace_minutes', models.PositiveIntegerField(default=15)),
                ('no_show_after_minutes', models.PositiveIntegerField(default=30)),
                ('missed_clock_out_after_minutes', models.PositiveIntegerField(default=120)),
                ('clock_in_location_mode', models.CharField(choices=[('off', 'Aus'), ('warn', 'Hinweis'), ('block', 'Blockieren')], default='block', max_length=10)),
                ('clock_out_location_mode', models.CharField(choices=[('off', 'Aus'), ('warn', 'Hinweis'), ('block', 'Blockieren')], default='block', max_length=10)),
                ('allow_unscheduled_clock_in', models.BooleanField(default=False)),
                ('required_break_after_minutes', models.PositiveIntegerField(default=360)),
                ('required_break_minutes', models.PositiveIntegerField(default=30)),
                ('default_break_paid', models.BooleanField(default=False)),
                ('auto_deduct_unpaid_breaks', models.BooleanField(default=False)),
                ('break_attestation_required', models.BooleanField(default=False)),
                ('end_of_shift_attestation_required', models.BooleanField(default=False)),
                ('terminal_photo_clock_in', models.BooleanField(default=False)),
                ('terminal_photo_clock_out', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='core.location')),
            ],
            options={'ordering': ['-priority', '-updated_at']},
        ),
        migrations.AddIndex(model_name='attendancepolicy', index=models.Index(fields=['active', 'location', 'priority'], name='att_policy_scope_idx')),
        migrations.CreateModel(
            name='AttendanceBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('running', 'Läuft'), ('completed', 'Beendet'), ('cancelled', 'Storniert')], default='planned', max_length=20)),
                ('source', models.CharField(choices=[('scheduled', 'Dienstplan'), ('manual', 'Mitarbeiter'), ('auto_deduct', 'Automatischer Abzug'), ('terminal', 'Terminal'), ('manager', 'Administration')], default='manual', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('scheduled_minutes', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('deducted_minutes', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_breaks_ended', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_breaks', to='core.timeentry')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_breaks_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(model_name='attendancebreak', index=models.Index(fields=['entry', 'status'], name='att_break_entry_idx')),
        migrations.CreateModel(
            name='AttendanceClockEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('clock_in', 'Einstempeln'), ('clock_out', 'Ausstempeln'), ('break_start', 'Pausenbeginn'), ('break_end', 'Pausenende')], max_length=20)),
                ('method', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobil'), ('terminal', 'Terminal'), ('manager', 'Administration'), ('api', 'API')], default='web', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='attendance/%Y/%m/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_events', to='core.timeentry')),
            ],
            options={'ordering': ['occurred_at']},
        ),
        migrations.AddIndex(model_name='attendanceclockevent', index=models.Index(fields=['entry', 'kind', 'occurred_at'], name='att_clock_event_idx')),
        migrations.CreateModel(
            name='AttendanceNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_type', models.CharField(choices=[('early_clock_in', 'Zu früh eingestempelt'), ('late_clock_in', 'Zu spät eingestempelt'), ('early_clock_out', 'Zu früh ausgestempelt'), ('late_clock_out', 'Zu spät ausgestempelt'), ('wrong_location', 'Falscher Standort'), ('missed_clock_in', 'Einstempeln fehlt'), ('missed_clock_out', 'Ausstempeln fehlt'), ('no_show', 'Nicht erschienen'), ('not_scheduled', 'Nicht eingeplant'), ('photo_missing', 'Foto fehlt'), ('break_missed', 'Pause fehlt'), ('break_short', 'Pause zu kurz'), ('attestation_missing', 'Bestätigung fehlt'), ('terminal_denied', 'Terminal-Zugriff abgelehnt')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Hinweis'), ('warning', 'Warnung'), ('critical', 'Kritisch')], default='warning', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('acknowledged', 'Gesehen'), ('resolved', 'Erledigt'), ('dismissed', 'Verworfen')], default='open', max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('value_minutes', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=180, unique=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=250)),
                ('break_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='core.attendancebreak')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notices', to='core.timeentry')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_attendance_notices', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notices', to='core.shift')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notices', to='core.workerprofile')),
            ],
            options={'ordering': ['-detected_at']},
        ),
        migrations.AddIndex(model_name='attendancenotice', index=models.Index(fields=['status', 'severity', 'detected_at'], name='att_notice_status_idx')),
        migrations.AddIndex(model_name='attendancenotice', index=models.Index(fields=['worker', 'notice_type'], name='att_notice_worker_idx')),
        migrations.CreateModel(
            name='AttendanceAttestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('break', 'Pausenbestätigung'), ('end_of_shift', 'Schichtende')], max_length=20)),
                ('answers', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('self_service', 'Mitarbeiterportal'), ('terminal', 'Terminal'), ('manager', 'Administration')], default='self_service', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='core.timeentry')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_attestations', to='core.workerprofile')),
            ],
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddConstraint(model_name='attendanceattestation', constraint=models.UniqueConstraint(fields=('entry', 'kind'), name='att_attestation_unique')),
        migrations.CreateModel(
            name='AttendanceTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_hash', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('photo_clock_in', models.BooleanField(default=False)),
                ('photo_clock_out', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_terminals_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_terminals', to='core.location')),
            ],
            options={'ordering': ['location__name', 'name']},
        ),
        migrations.AddIndex(model_name='attendanceterminal', index=models.Index(fields=['active', 'location'], name='att_terminal_scope_idx')),
        migrations.RunPython(seed_policy, migrations.RunPython.noop),
    ]
